### ISSUE TITLE
EPIC: Display Black Ice Weapons End to End (locally)

### ISSUE THREAD

**Issue by dylanquesada** [dylanquesada/black-ice-tracker#14]
Acceptance criteria:
- [x] Fetch response for GET ```api/guns``` on Front End
- [x] Web API handles response and queries DB
- [x] Display response data on FE
